### ISSUE TITLE
Tests failing for core.rb

### ISSUE THREAD

**Issue by kotp** [wesley974/rubygame#4]
```
[rubygame] ruby -Ispec -Ilib -r minitest/autorun spec/core_spec.rb
Run options: --seed 53194

# Running:

EE

Finished in 0.001318s, 1517.2124 runs/s, 0.0000 assertions/s.

  1) Error:
Core#test_0001_should have default value tries as 0:
NoMethodError: undefined method `eql' for #<#<Class:0x00000001037158>:0x00000000e981f8>
Did you mean?  eql?
    spec/core_spec.rb:9:in `block (2 levels) in <main>'


  2) Error:
Core#test_0002_should have secret range in between 1 and 100:
NoMethodError: undefined method `be_between' for #<#<Class:0x00000001037158>:0x00000000e97aa0>
    spec/core_spec.rb:13:in `block (2 levels) in <main>'

2 runs, 0 assertions, 0 failures, 2 errors, 0 skips
```

Running tests is more complicated than it needs to be.  A rake task could be provided for testing.

**Comment by kotp** [comment]
PR #2 solves the failing tests, with improvements.
